# Плагин DoorLock от _joones (https://github.com/SJones-BWGY/DoorLock)
# Обновил и перевел на русский язык: l1ratch (https://github.com/l1ratch)

# Режим обновления
# true = Включить проверку обновлений
# false = Отключить проверку обновлений
update: true

# Включение и отключение элементов (true = включено; false = отключено)
items:
    key: true # CustomModelData: 9999101
    blocklocker: true # CustomModelData: 9999102
    doordrill: true # CustomModelData: 9999103